name: 'TerraformWorkflowPoc'
 
on:
  push:
    branches:
    - main  
jobs:
  tflint:
    name: 'TFlint'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    steps:
      - name: checkoutCode
        uses: actions/checkout@v2
      - name: tflint
        uses: reviewdog/action-tflint@master
        with:
          github_token: ${{ secrets.github_token }}

  plan:
    name: 'TFplan'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    runs-on: ubuntu-latest
    needs: [tflint]
    defaults:
      run:
        shell: bash
 
    steps:
    - name: CheckoutCode
      uses: actions/checkout@v2
         
    - name: set up terraform
      run: |
        wget https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip
        unzip terraform_1.3.7_linux_amd64.zip
        mv terraform /usr/local/bin/
    
    - name: terraform plan
      id: init
      run: |
        pwd
        ls -la
        terraform init
        terraform plan var-file=dev.tfvars

  apply:
    name: 'TFapply'
    needs: [plan,tflint]
    runs-on: ubuntu-latest
    environment:
      name: dev
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    defaults:
      run:
        shell: bash
    steps:
    - name: CheckoutCode
      uses: actions/checkout@v2
    - name: set up terraform
      run: |
        wget https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip
        unzip terraform_1.3.7_linux_amd64.zip
        mv terraform /usr/local/bin/
    - name: terraform Apply
      id: apply
      run: |
        terraform init
        terraform apply var-file="dev.tfvars" -auto-approve
    