name: 'TerraformPlan'
 
on:
  push:
    branches:
    - main  
jobs:
  plan:
    name: 'plan Terraform'
    runs-on: ubuntu-latest
 
    defaults:
      run:
        shell: bash
 
    steps:
    - name: CheckoutCode
      uses: actions/checkout@v2
         
    - name: set up terraform
      run: |
        wget https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip
        unzip terraform_1.3.7_linux_amd64.zip
        mv terraform /usr/local/bin/
    
    - name: terraform plan
      id: init
      run: |
        terraform init